name: Pull Request Integration
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👋 A ${{ github.event_name }} event running on a ${{ runner.os }} server."
      - run: echo "🔎 The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.2.0'

      - uses: ./.github/workflows/_build.yml
      - uses: ./.github/workflows/_unit_coverage.yml

      - run: echo "🖥️ Run e2e testing" && yarn deploy:e2e
      - run: echo "✅ Congratulations!"
